# Generated by Django 4.1.2 on 2023-01-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_block_alter_user_phone_number_otp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
