# Generated by Django 4.1.2 on 2023-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productgallery_default_alter_productgallery_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
