# Generated by Django 4.1.2 on 2023-02-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat_Off',
        ),
    ]
