# Generated by Django 4.1.2 on 2023-01-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductGallery',
        ),
    ]
