# Generated by Django 4.1.2 on 2023-01-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0007_vary_product_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
        migrations.DeleteModel(
            name='Vary',
        ),
    ]
