# Generated by Django 4.1.2 on 2023-01-26 07:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0010_productimage_delete_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('White', 'White'), ('Green', 'Green')], default='', max_length=10),
        ),
    ]
