# Generated by Django 4.1.2 on 2023-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0015_remove_product_color_delete_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offers',
            field=models.IntegerField(default=50,null=True),
        ),
    ]
