# Generated by Django 4.1.2 on 2023-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0017_alter_product_is_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_offers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
