# Generated by Django 4.1.2 on 2023-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0019_alter_product_is_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_offers',
            field=models.FloatField(default=50, null=True),
        ),
    ]
