# Generated by Django 4.1.2 on 2023-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0022_alter_product_is_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_offers',
            new_name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
