# Generated by Django 4.1.2 on 2023-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0023_rename_is_offers_product_offer_product_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offered_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
