# Generated by Django 4.1.2 on 2023-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0025_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_offer',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_amount',
            field=models.FloatField(default=100, null=True),
        ),
    ]
