# Generated by Django 4.1.2 on 2023-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0026_category_is_offer_category_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_offer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
