# Generated by Django 4.1.2 on 2023-01-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0015_remove_product_color_delete_color'),
        ('cart', '0002_rename_discount_prize_coupon_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='admin_custom.product'),
        ),
    ]
