# Generated by Django 4.1.2 on 2023-01-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='pincode',
        ),
    ]
